package works.com.testapp;

import android.support.v7.app.ActionBarActivity;
import android.os.Bundle;
import android.util.EventLog;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.TextView;


public class MainActivity extends ActionBarActivity {

    //TAG is used to annotate the logs that we use for debugging using logcat. It helps us filter
    // out logs generated by the OS and other apps running in the background

    String TAG = "Test";
    TextView textView;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        textView = (TextView) findViewById(R.id.textView);
    }


    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }

    @Override
    protected void onResume() {
        super.onResume();
        Log.d(TAG, "Resume!");
    }

    @Override
    protected void onPause()
    {
        super.onPause();
        Log.d(TAG,"Paused!");
    }

    public void firstButtonClicked (View v)
    {
        Log.d(TAG,"First Button");
        textView.setText("First");
    }

    public void secondButtonClicked (View v)
    {
        Log.d(TAG,"Second Button");
        textView.setText("Second");
    }
}

